### ISSUE TITLE
Fix code scanning alert - Update Actions Workflow to set minimum required permissions

### ISSUE THREAD

**Issue by Hampton-Black** [rwa-project/smart-contracts#6]
Tracking issue for:
- [ ] https://github.com/rwa-project/smart-contracts/security/code-scanning/1

Recommendation:
```
jobs:
  my-job:
    permissions:
      contents: read
      pull-requests: write
      issues: write
```
